name: Terraform PR (dev)

on:
    pull_request:
        paths:
            - "infrastructure/**"
            - ".github/workflows/**"
    workflow_dispatch:
permissions:
    contents: read 
    id-token: write # required for AWS OIDC
    pull-requests: write # to write plan to PR
env:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"
    WORKDIR: infrastructure/root
    TF_ENV: dev
    AWS_REGION: us-east-2

jobs:
    validate:
        name: Validate + Lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.WORKDIR}}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_wrapper: false
            
            - name: Setup TFLint
              uses: terraform-linters/setup-tflint@v4
              with:
                tflint_version: latest
            - name: Terraform fmt (check)
              run: terraform fmt -check -recursive
            
            # validate without needing backend/AWS credentials
            - name: Terraform init (no backend)
              run: terraform init -backend=false
            
            - name: Terraform validate
              run: terraform validate
            
            - name: TFLint init
              run: tflint --init
            
            - name: TFLint
              run: tflint --recursive

    plan-dev:
        name: Plan (dev)
        runs-on: ubuntu-latest
        needs: validate
        defaults:
            run:
                working-directory: ${{ env.WORKDIR }}

        steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
              terraform_wrapper: false

        - name: Configure AWS credentials (OIDC)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ vars.AWS_ROLE_ARN_PLAN }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Terraform init (remote backend)
          run: terraform init -backend-config=backend.hcl

        - name: Select workspace
          run: |
            terraform workspace new "$TF_ENV" || true
            terraform workspace select "$TF_ENV"

        - name: Terraform plan
          run: |
            terraform plan -var-file=../environments/dev.tfvars -no-color | tee plan.txt

        - name: Upload plan artifact
          uses: actions/upload-artifact@v4
          with:
            name: tfplan-dev
            path: ${{ env.WORKDIR }}/plan.txt

        - name: Comment plan on PR
          if: github.event_name == 'pull_request'
          uses: actions/github-script@v8
          with:
            script: |
                const fs = require('fs');
                let plan = fs.readFileSync('${{ env.WORKDIR }}/plan.txt', 'utf8');
                const max = 65000; // GitHub comment limit ~65536 chars :contentReference[oaicite:3]{index=3}
                if (plan.length > max) plan = plan.slice(0, max) + "\n\n...truncated...\n";
                const body = `### Terraform plan (dev)\n\n\`\`\`\n${plan}\n\`\`\``;

                await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body
                });